# NumPy Refresher 
Numpy is the fundamental package for scientific computing in Python. 

It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

In [7]:
import numpy as np 

## Array creation

In [8]:
# It's possible to create an array directly from a python list

vector = np.array([1, 2, 3])   # Create a rank 1 array i.e a vector

# Looking at the type and shape of this new vector object
print(type(vector))            # Prints "<class 'numpy.ndarray'>"
print(vector.shape)            # Prints "(3,)" 

<class 'numpy.ndarray'>
(3,)


In [9]:
# It's possible to access directly an element by indexing
print(vector[0])               # Prints 1 it's 0 based indexing
print(vector[2])               # Prints 3

1
3


In [10]:
# It's also possible to change an element of this array by indexing
vector[0] = 5                  # Change an element of the array
print(vector)                  # Prints "[5, 2, 3]"

[5 2 3]


In [11]:
# It's also possible to create matrix or tensor
matrix = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array i.e a matrix
print(matrix.shape)                     # Prints "(2, 3)" note it's a row-major array
print(matrix[0, 0])                     # Prints "1 2 4"

# It also provide some builtin way to create matrix or tensor
identity = np.eye(2)                    # Create a 2x2 identity matrix
print(identity)                                # Prints "[[ 1.  0.]
                                        #          [ 0.  1.]]"

(2, 3)
1
[[1. 0.]
 [0. 1.]]


In [12]:
tensor = np.zeros((2,2,2))   # Create an tensor of shape [2,2,2] of all zeros
print(tensor)                # Prints [[[0. 0.]
                             #          [0. 0.]]
                             #          [[0. 0.]
                             #          [0. 0.]]]      

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [13]:
random_tensor = np.random.random((2,3,4)) # Should output random float 
print(random_tensor)                      # in the shape [2,3,4]

[[[0.93944818 0.88410888 0.5189561  0.13900495]
  [0.8617814  0.31840763 0.34943775 0.63781751]
  [0.43311736 0.4080262  0.53492741 0.05812257]]

 [[0.57007189 0.51805189 0.83640699 0.68348963]
  [0.14983632 0.51358727 0.43516613 0.07686464]
  [0.42031885 0.66835171 0.07127821 0.32511526]]]


## Some exercices 

In [15]:

# Create a vector with 5 elements from 0 to 4
def my_first_array():
  return np.array([0,1,2,3,4])

print(my_first_array())


[0 1 2 3 4]


In [20]:
# Create a matrix 2x5 with 10 elements from 0 to 9
def my_first_matrix():
  return np.arange(10).reshape(2,5)

print(my_first_matrix())

[[0 1 2 3 4]
 [5 6 7 8 9]]
